// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface GroupJoinedQueryReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupJoinedQueryReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 userId = 1;</code>
   * @return The userId.
   */
  int getUserId();
}
