// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface GroupQuitReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupQuitReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 groupId = 1;</code>
   * @return The groupId.
   */
  int getGroupId();

  /**
   * <code>int32 userId = 2;</code>
   * @return The userId.
   */
  int getUserId();
}
