// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

public interface GroupMemberQueryResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupMemberQueryRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>repeated int32 userId = 3;</code>
   * @return A list containing the userId.
   */
  java.util.List<java.lang.Integer> getUserIdList();
  /**
   * <code>repeated int32 userId = 3;</code>
   * @return The count of userId.
   */
  int getUserIdCount();
  /**
   * <code>repeated int32 userId = 3;</code>
   * @param index The index of the element to return.
   * @return The userId at the given index.
   */
  int getUserId(int index);
}
