// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface GroupJoinedQueryResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupJoinedQueryRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>bool status = 1;</code>
   * @return The status.
   */
  boolean getStatus();

  /**
   * <code>string reason = 2;</code>
   * @return The reason.
   */
  java.lang.String getReason();
  /**
   * <code>string reason = 2;</code>
   * @return The bytes for reason.
   */
  com.google.protobuf.ByteString
      getReasonBytes();

  /**
   * <code>repeated int32 groupId = 3;</code>
   * @return A list containing the groupId.
   */
  java.util.List<java.lang.Integer> getGroupIdList();
  /**
   * <code>repeated int32 groupId = 3;</code>
   * @return The count of groupId.
   */
  int getGroupIdCount();
  /**
   * <code>repeated int32 groupId = 3;</code>
   * @param index The index of the element to return.
   * @return The groupId at the given index.
   */
  int getGroupId(int index);
}
