// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface GroupJoinReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupJoinReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 joinId = 1;</code>
   * @return The joinId.
   */
  int getJoinId();

  /**
   * <code>int32 userId = 2;</code>
   * @return The userId.
   */
  int getUserId();
}
