// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface GroupMemberQueryReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupMemberQueryReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 groupId = 1;</code>
   * @return The groupId.
   */
  int getGroupId();
}
