// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

public interface GroupCreateReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.GroupCreateReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 groupId = 1;</code>
   * @return The groupId.
   */
  int getGroupId();

  /**
   * <code>int32 userId = 2;</code>
   * @return The userId.
   */
  int getUserId();
}
