// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface LoginResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.LoginRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chat.simple.LoginRes.LoginStatus status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.chat.simple.LoginRes.LoginStatus status = 1;</code>
   * @return The status.
   */
  com.example.message.LoginRes.LoginStatus getStatus();

  /**
   * <code>string response = 2;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 2;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();

  /**
   * <code>int32 sUserId = 3;</code>
   * @return The sUserId.
   */
  int getSUserId();
}
