// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

/**
 * Protobuf type {@code chat.simple.Message}
 */
public final class Message extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:chat.simple.Message)
    MessageOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Message.newBuilder() to construct.
  private Message(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Message() {
    messageType_ = 0;
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Message();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Message(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 8: {
            int rawValue = input.readEnum();

            messageType_ = rawValue;
            break;
          }
          case 18: {
            com.example.message.LoginReq.Builder subBuilder = null;
            if (messageBodyCase_ == 2) {
              subBuilder = ((com.example.message.LoginReq) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.example.message.LoginReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.message.LoginReq) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 2;
            break;
          }
          case 26: {
            com.example.message.MsgReq.Builder subBuilder = null;
            if (messageBodyCase_ == 3) {
              subBuilder = ((com.example.message.MsgReq) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.example.message.MsgReq.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.message.MsgReq) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 3;
            break;
          }
          case 34: {
            com.example.message.MsgRes.Builder subBuilder = null;
            if (messageBodyCase_ == 4) {
              subBuilder = ((com.example.message.MsgRes) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.example.message.MsgRes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.message.MsgRes) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 4;
            break;
          }
          case 42: {
            com.example.message.LoginRes.Builder subBuilder = null;
            if (messageBodyCase_ == 5) {
              subBuilder = ((com.example.message.LoginRes) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.example.message.LoginRes.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.message.LoginRes) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 5;
            break;
          }
          case 50: {
            com.example.message.MsgRX.Builder subBuilder = null;
            if (messageBodyCase_ == 6) {
              subBuilder = ((com.example.message.MsgRX) messageBody_).toBuilder();
            }
            messageBody_ =
                input.readMessage(com.example.message.MsgRX.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom((com.example.message.MsgRX) messageBody_);
              messageBody_ = subBuilder.buildPartial();
            }
            messageBodyCase_ = 6;
            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.example.message.MessageProto.internal_static_chat_simple_Message_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.example.message.MessageProto.internal_static_chat_simple_Message_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.example.message.Message.class, com.example.message.Message.Builder.class);
  }

  /**
   * Protobuf enum {@code chat.simple.Message.MessageType}
   */
  public enum MessageType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>LOGIN_REQ = 0;</code>
     */
    LOGIN_REQ(0),
    /**
     * <code>LOGIN_RES = 1;</code>
     */
    LOGIN_RES(1),
    /**
     * <code>MSG_REQ = 2;</code>
     */
    MSG_REQ(2),
    /**
     * <code>MSG_RES = 3;</code>
     */
    MSG_RES(3),
    /**
     * <code>MSG_RX = 4;</code>
     */
    MSG_RX(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>LOGIN_REQ = 0;</code>
     */
    public static final int LOGIN_REQ_VALUE = 0;
    /**
     * <code>LOGIN_RES = 1;</code>
     */
    public static final int LOGIN_RES_VALUE = 1;
    /**
     * <code>MSG_REQ = 2;</code>
     */
    public static final int MSG_REQ_VALUE = 2;
    /**
     * <code>MSG_RES = 3;</code>
     */
    public static final int MSG_RES_VALUE = 3;
    /**
     * <code>MSG_RX = 4;</code>
     */
    public static final int MSG_RX_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageType valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static MessageType forNumber(int value) {
      switch (value) {
        case 0: return LOGIN_REQ;
        case 1: return LOGIN_RES;
        case 2: return MSG_REQ;
        case 3: return MSG_RES;
        case 4: return MSG_RX;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        MessageType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
            public MessageType findValueByNumber(int number) {
              return MessageType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.example.message.Message.getDescriptor().getEnumTypes().get(0);
    }

    private static final MessageType[] VALUES = values();

    public static MessageType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private MessageType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:chat.simple.Message.MessageType)
  }

  private int messageBodyCase_ = 0;
  private java.lang.Object messageBody_;
  public enum MessageBodyCase
      implements com.google.protobuf.Internal.EnumLite,
          com.google.protobuf.AbstractMessage.InternalOneOfEnum {
    LOGINREQ(2),
    MSGREQ(3),
    MSGRES(4),
    LOGINRES(5),
    MSGRX(6),
    MESSAGEBODY_NOT_SET(0);
    private final int value;
    private MessageBodyCase(int value) {
      this.value = value;
    }
    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static MessageBodyCase valueOf(int value) {
      return forNumber(value);
    }

    public static MessageBodyCase forNumber(int value) {
      switch (value) {
        case 2: return LOGINREQ;
        case 3: return MSGREQ;
        case 4: return MSGRES;
        case 5: return LOGINRES;
        case 6: return MSGRX;
        case 0: return MESSAGEBODY_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public MessageBodyCase
  getMessageBodyCase() {
    return MessageBodyCase.forNumber(
        messageBodyCase_);
  }

  public static final int MESSAGETYPE_FIELD_NUMBER = 1;
  private int messageType_;
  /**
   * <code>.chat.simple.Message.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  @java.lang.Override public int getMessageTypeValue() {
    return messageType_;
  }
  /**
   * <code>.chat.simple.Message.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  @java.lang.Override public com.example.message.Message.MessageType getMessageType() {
    @SuppressWarnings("deprecation")
    com.example.message.Message.MessageType result = com.example.message.Message.MessageType.valueOf(messageType_);
    return result == null ? com.example.message.Message.MessageType.UNRECOGNIZED : result;
  }

  public static final int LOGINREQ_FIELD_NUMBER = 2;
  /**
   * <code>.chat.simple.LoginReq loginReq = 2;</code>
   * @return Whether the loginReq field is set.
   */
  @java.lang.Override
  public boolean hasLoginReq() {
    return messageBodyCase_ == 2;
  }
  /**
   * <code>.chat.simple.LoginReq loginReq = 2;</code>
   * @return The loginReq.
   */
  @java.lang.Override
  public com.example.message.LoginReq getLoginReq() {
    if (messageBodyCase_ == 2) {
       return (com.example.message.LoginReq) messageBody_;
    }
    return com.example.message.LoginReq.getDefaultInstance();
  }
  /**
   * <code>.chat.simple.LoginReq loginReq = 2;</code>
   */
  @java.lang.Override
  public com.example.message.LoginReqOrBuilder getLoginReqOrBuilder() {
    if (messageBodyCase_ == 2) {
       return (com.example.message.LoginReq) messageBody_;
    }
    return com.example.message.LoginReq.getDefaultInstance();
  }

  public static final int MSGREQ_FIELD_NUMBER = 3;
  /**
   * <code>.chat.simple.MsgReq msgReq = 3;</code>
   * @return Whether the msgReq field is set.
   */
  @java.lang.Override
  public boolean hasMsgReq() {
    return messageBodyCase_ == 3;
  }
  /**
   * <code>.chat.simple.MsgReq msgReq = 3;</code>
   * @return The msgReq.
   */
  @java.lang.Override
  public com.example.message.MsgReq getMsgReq() {
    if (messageBodyCase_ == 3) {
       return (com.example.message.MsgReq) messageBody_;
    }
    return com.example.message.MsgReq.getDefaultInstance();
  }
  /**
   * <code>.chat.simple.MsgReq msgReq = 3;</code>
   */
  @java.lang.Override
  public com.example.message.MsgReqOrBuilder getMsgReqOrBuilder() {
    if (messageBodyCase_ == 3) {
       return (com.example.message.MsgReq) messageBody_;
    }
    return com.example.message.MsgReq.getDefaultInstance();
  }

  public static final int MSGRES_FIELD_NUMBER = 4;
  /**
   * <code>.chat.simple.MsgRes msgRes = 4;</code>
   * @return Whether the msgRes field is set.
   */
  @java.lang.Override
  public boolean hasMsgRes() {
    return messageBodyCase_ == 4;
  }
  /**
   * <code>.chat.simple.MsgRes msgRes = 4;</code>
   * @return The msgRes.
   */
  @java.lang.Override
  public com.example.message.MsgRes getMsgRes() {
    if (messageBodyCase_ == 4) {
       return (com.example.message.MsgRes) messageBody_;
    }
    return com.example.message.MsgRes.getDefaultInstance();
  }
  /**
   * <code>.chat.simple.MsgRes msgRes = 4;</code>
   */
  @java.lang.Override
  public com.example.message.MsgResOrBuilder getMsgResOrBuilder() {
    if (messageBodyCase_ == 4) {
       return (com.example.message.MsgRes) messageBody_;
    }
    return com.example.message.MsgRes.getDefaultInstance();
  }

  public static final int LOGINRES_FIELD_NUMBER = 5;
  /**
   * <code>.chat.simple.LoginRes loginRes = 5;</code>
   * @return Whether the loginRes field is set.
   */
  @java.lang.Override
  public boolean hasLoginRes() {
    return messageBodyCase_ == 5;
  }
  /**
   * <code>.chat.simple.LoginRes loginRes = 5;</code>
   * @return The loginRes.
   */
  @java.lang.Override
  public com.example.message.LoginRes getLoginRes() {
    if (messageBodyCase_ == 5) {
       return (com.example.message.LoginRes) messageBody_;
    }
    return com.example.message.LoginRes.getDefaultInstance();
  }
  /**
   * <code>.chat.simple.LoginRes loginRes = 5;</code>
   */
  @java.lang.Override
  public com.example.message.LoginResOrBuilder getLoginResOrBuilder() {
    if (messageBodyCase_ == 5) {
       return (com.example.message.LoginRes) messageBody_;
    }
    return com.example.message.LoginRes.getDefaultInstance();
  }

  public static final int MSGRX_FIELD_NUMBER = 6;
  /**
   * <code>.chat.simple.MsgRX msgRX = 6;</code>
   * @return Whether the msgRX field is set.
   */
  @java.lang.Override
  public boolean hasMsgRX() {
    return messageBodyCase_ == 6;
  }
  /**
   * <code>.chat.simple.MsgRX msgRX = 6;</code>
   * @return The msgRX.
   */
  @java.lang.Override
  public com.example.message.MsgRX getMsgRX() {
    if (messageBodyCase_ == 6) {
       return (com.example.message.MsgRX) messageBody_;
    }
    return com.example.message.MsgRX.getDefaultInstance();
  }
  /**
   * <code>.chat.simple.MsgRX msgRX = 6;</code>
   */
  @java.lang.Override
  public com.example.message.MsgRXOrBuilder getMsgRXOrBuilder() {
    if (messageBodyCase_ == 6) {
       return (com.example.message.MsgRX) messageBody_;
    }
    return com.example.message.MsgRX.getDefaultInstance();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (messageType_ != com.example.message.Message.MessageType.LOGIN_REQ.getNumber()) {
      output.writeEnum(1, messageType_);
    }
    if (messageBodyCase_ == 2) {
      output.writeMessage(2, (com.example.message.LoginReq) messageBody_);
    }
    if (messageBodyCase_ == 3) {
      output.writeMessage(3, (com.example.message.MsgReq) messageBody_);
    }
    if (messageBodyCase_ == 4) {
      output.writeMessage(4, (com.example.message.MsgRes) messageBody_);
    }
    if (messageBodyCase_ == 5) {
      output.writeMessage(5, (com.example.message.LoginRes) messageBody_);
    }
    if (messageBodyCase_ == 6) {
      output.writeMessage(6, (com.example.message.MsgRX) messageBody_);
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (messageType_ != com.example.message.Message.MessageType.LOGIN_REQ.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, messageType_);
    }
    if (messageBodyCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, (com.example.message.LoginReq) messageBody_);
    }
    if (messageBodyCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, (com.example.message.MsgReq) messageBody_);
    }
    if (messageBodyCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(4, (com.example.message.MsgRes) messageBody_);
    }
    if (messageBodyCase_ == 5) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, (com.example.message.LoginRes) messageBody_);
    }
    if (messageBodyCase_ == 6) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(6, (com.example.message.MsgRX) messageBody_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.example.message.Message)) {
      return super.equals(obj);
    }
    com.example.message.Message other = (com.example.message.Message) obj;

    if (messageType_ != other.messageType_) return false;
    if (!getMessageBodyCase().equals(other.getMessageBodyCase())) return false;
    switch (messageBodyCase_) {
      case 2:
        if (!getLoginReq()
            .equals(other.getLoginReq())) return false;
        break;
      case 3:
        if (!getMsgReq()
            .equals(other.getMsgReq())) return false;
        break;
      case 4:
        if (!getMsgRes()
            .equals(other.getMsgRes())) return false;
        break;
      case 5:
        if (!getLoginRes()
            .equals(other.getLoginRes())) return false;
        break;
      case 6:
        if (!getMsgRX()
            .equals(other.getMsgRX())) return false;
        break;
      case 0:
      default:
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + MESSAGETYPE_FIELD_NUMBER;
    hash = (53 * hash) + messageType_;
    switch (messageBodyCase_) {
      case 2:
        hash = (37 * hash) + LOGINREQ_FIELD_NUMBER;
        hash = (53 * hash) + getLoginReq().hashCode();
        break;
      case 3:
        hash = (37 * hash) + MSGREQ_FIELD_NUMBER;
        hash = (53 * hash) + getMsgReq().hashCode();
        break;
      case 4:
        hash = (37 * hash) + MSGRES_FIELD_NUMBER;
        hash = (53 * hash) + getMsgRes().hashCode();
        break;
      case 5:
        hash = (37 * hash) + LOGINRES_FIELD_NUMBER;
        hash = (53 * hash) + getLoginRes().hashCode();
        break;
      case 6:
        hash = (37 * hash) + MSGRX_FIELD_NUMBER;
        hash = (53 * hash) + getMsgRX().hashCode();
        break;
      case 0:
      default:
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.example.message.Message parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.message.Message parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.message.Message parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.message.Message parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.message.Message parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.example.message.Message parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.example.message.Message parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.message.Message parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.message.Message parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.example.message.Message parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.example.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.example.message.Message parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.example.message.Message prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code chat.simple.Message}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:chat.simple.Message)
      com.example.message.MessageOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.example.message.MessageProto.internal_static_chat_simple_Message_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.example.message.MessageProto.internal_static_chat_simple_Message_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.example.message.Message.class, com.example.message.Message.Builder.class);
    }

    // Construct using com.example.message.Message.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      messageType_ = 0;

      messageBodyCase_ = 0;
      messageBody_ = null;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.example.message.MessageProto.internal_static_chat_simple_Message_descriptor;
    }

    @java.lang.Override
    public com.example.message.Message getDefaultInstanceForType() {
      return com.example.message.Message.getDefaultInstance();
    }

    @java.lang.Override
    public com.example.message.Message build() {
      com.example.message.Message result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.example.message.Message buildPartial() {
      com.example.message.Message result = new com.example.message.Message(this);
      result.messageType_ = messageType_;
      if (messageBodyCase_ == 2) {
        if (loginReqBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = loginReqBuilder_.build();
        }
      }
      if (messageBodyCase_ == 3) {
        if (msgReqBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = msgReqBuilder_.build();
        }
      }
      if (messageBodyCase_ == 4) {
        if (msgResBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = msgResBuilder_.build();
        }
      }
      if (messageBodyCase_ == 5) {
        if (loginResBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = loginResBuilder_.build();
        }
      }
      if (messageBodyCase_ == 6) {
        if (msgRXBuilder_ == null) {
          result.messageBody_ = messageBody_;
        } else {
          result.messageBody_ = msgRXBuilder_.build();
        }
      }
      result.messageBodyCase_ = messageBodyCase_;
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.example.message.Message) {
        return mergeFrom((com.example.message.Message)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.example.message.Message other) {
      if (other == com.example.message.Message.getDefaultInstance()) return this;
      if (other.messageType_ != 0) {
        setMessageTypeValue(other.getMessageTypeValue());
      }
      switch (other.getMessageBodyCase()) {
        case LOGINREQ: {
          mergeLoginReq(other.getLoginReq());
          break;
        }
        case MSGREQ: {
          mergeMsgReq(other.getMsgReq());
          break;
        }
        case MSGRES: {
          mergeMsgRes(other.getMsgRes());
          break;
        }
        case LOGINRES: {
          mergeLoginRes(other.getLoginRes());
          break;
        }
        case MSGRX: {
          mergeMsgRX(other.getMsgRX());
          break;
        }
        case MESSAGEBODY_NOT_SET: {
          break;
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.example.message.Message parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.example.message.Message) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int messageBodyCase_ = 0;
    private java.lang.Object messageBody_;
    public MessageBodyCase
        getMessageBodyCase() {
      return MessageBodyCase.forNumber(
          messageBodyCase_);
    }

    public Builder clearMessageBody() {
      messageBodyCase_ = 0;
      messageBody_ = null;
      onChanged();
      return this;
    }


    private int messageType_ = 0;
    /**
     * <code>.chat.simple.Message.MessageType messageType = 1;</code>
     * @return The enum numeric value on the wire for messageType.
     */
    @java.lang.Override public int getMessageTypeValue() {
      return messageType_;
    }
    /**
     * <code>.chat.simple.Message.MessageType messageType = 1;</code>
     * @param value The enum numeric value on the wire for messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageTypeValue(int value) {
      
      messageType_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>.chat.simple.Message.MessageType messageType = 1;</code>
     * @return The messageType.
     */
    @java.lang.Override
    public com.example.message.Message.MessageType getMessageType() {
      @SuppressWarnings("deprecation")
      com.example.message.Message.MessageType result = com.example.message.Message.MessageType.valueOf(messageType_);
      return result == null ? com.example.message.Message.MessageType.UNRECOGNIZED : result;
    }
    /**
     * <code>.chat.simple.Message.MessageType messageType = 1;</code>
     * @param value The messageType to set.
     * @return This builder for chaining.
     */
    public Builder setMessageType(com.example.message.Message.MessageType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      messageType_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.chat.simple.Message.MessageType messageType = 1;</code>
     * @return This builder for chaining.
     */
    public Builder clearMessageType() {
      
      messageType_ = 0;
      onChanged();
      return this;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.LoginReq, com.example.message.LoginReq.Builder, com.example.message.LoginReqOrBuilder> loginReqBuilder_;
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     * @return Whether the loginReq field is set.
     */
    @java.lang.Override
    public boolean hasLoginReq() {
      return messageBodyCase_ == 2;
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     * @return The loginReq.
     */
    @java.lang.Override
    public com.example.message.LoginReq getLoginReq() {
      if (loginReqBuilder_ == null) {
        if (messageBodyCase_ == 2) {
          return (com.example.message.LoginReq) messageBody_;
        }
        return com.example.message.LoginReq.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 2) {
          return loginReqBuilder_.getMessage();
        }
        return com.example.message.LoginReq.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    public Builder setLoginReq(com.example.message.LoginReq value) {
      if (loginReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        loginReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    public Builder setLoginReq(
        com.example.message.LoginReq.Builder builderForValue) {
      if (loginReqBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        loginReqBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    public Builder mergeLoginReq(com.example.message.LoginReq value) {
      if (loginReqBuilder_ == null) {
        if (messageBodyCase_ == 2 &&
            messageBody_ != com.example.message.LoginReq.getDefaultInstance()) {
          messageBody_ = com.example.message.LoginReq.newBuilder((com.example.message.LoginReq) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 2) {
          loginReqBuilder_.mergeFrom(value);
        }
        loginReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 2;
      return this;
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    public Builder clearLoginReq() {
      if (loginReqBuilder_ == null) {
        if (messageBodyCase_ == 2) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 2) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        loginReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    public com.example.message.LoginReq.Builder getLoginReqBuilder() {
      return getLoginReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    @java.lang.Override
    public com.example.message.LoginReqOrBuilder getLoginReqOrBuilder() {
      if ((messageBodyCase_ == 2) && (loginReqBuilder_ != null)) {
        return loginReqBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 2) {
          return (com.example.message.LoginReq) messageBody_;
        }
        return com.example.message.LoginReq.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.LoginReq loginReq = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.LoginReq, com.example.message.LoginReq.Builder, com.example.message.LoginReqOrBuilder> 
        getLoginReqFieldBuilder() {
      if (loginReqBuilder_ == null) {
        if (!(messageBodyCase_ == 2)) {
          messageBody_ = com.example.message.LoginReq.getDefaultInstance();
        }
        loginReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.message.LoginReq, com.example.message.LoginReq.Builder, com.example.message.LoginReqOrBuilder>(
                (com.example.message.LoginReq) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 2;
      onChanged();;
      return loginReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.MsgReq, com.example.message.MsgReq.Builder, com.example.message.MsgReqOrBuilder> msgReqBuilder_;
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     * @return Whether the msgReq field is set.
     */
    @java.lang.Override
    public boolean hasMsgReq() {
      return messageBodyCase_ == 3;
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     * @return The msgReq.
     */
    @java.lang.Override
    public com.example.message.MsgReq getMsgReq() {
      if (msgReqBuilder_ == null) {
        if (messageBodyCase_ == 3) {
          return (com.example.message.MsgReq) messageBody_;
        }
        return com.example.message.MsgReq.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 3) {
          return msgReqBuilder_.getMessage();
        }
        return com.example.message.MsgReq.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    public Builder setMsgReq(com.example.message.MsgReq value) {
      if (msgReqBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        msgReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    public Builder setMsgReq(
        com.example.message.MsgReq.Builder builderForValue) {
      if (msgReqBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        msgReqBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    public Builder mergeMsgReq(com.example.message.MsgReq value) {
      if (msgReqBuilder_ == null) {
        if (messageBodyCase_ == 3 &&
            messageBody_ != com.example.message.MsgReq.getDefaultInstance()) {
          messageBody_ = com.example.message.MsgReq.newBuilder((com.example.message.MsgReq) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 3) {
          msgReqBuilder_.mergeFrom(value);
        }
        msgReqBuilder_.setMessage(value);
      }
      messageBodyCase_ = 3;
      return this;
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    public Builder clearMsgReq() {
      if (msgReqBuilder_ == null) {
        if (messageBodyCase_ == 3) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 3) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        msgReqBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    public com.example.message.MsgReq.Builder getMsgReqBuilder() {
      return getMsgReqFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    @java.lang.Override
    public com.example.message.MsgReqOrBuilder getMsgReqOrBuilder() {
      if ((messageBodyCase_ == 3) && (msgReqBuilder_ != null)) {
        return msgReqBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 3) {
          return (com.example.message.MsgReq) messageBody_;
        }
        return com.example.message.MsgReq.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.MsgReq msgReq = 3;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.MsgReq, com.example.message.MsgReq.Builder, com.example.message.MsgReqOrBuilder> 
        getMsgReqFieldBuilder() {
      if (msgReqBuilder_ == null) {
        if (!(messageBodyCase_ == 3)) {
          messageBody_ = com.example.message.MsgReq.getDefaultInstance();
        }
        msgReqBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.message.MsgReq, com.example.message.MsgReq.Builder, com.example.message.MsgReqOrBuilder>(
                (com.example.message.MsgReq) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 3;
      onChanged();;
      return msgReqBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.MsgRes, com.example.message.MsgRes.Builder, com.example.message.MsgResOrBuilder> msgResBuilder_;
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     * @return Whether the msgRes field is set.
     */
    @java.lang.Override
    public boolean hasMsgRes() {
      return messageBodyCase_ == 4;
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     * @return The msgRes.
     */
    @java.lang.Override
    public com.example.message.MsgRes getMsgRes() {
      if (msgResBuilder_ == null) {
        if (messageBodyCase_ == 4) {
          return (com.example.message.MsgRes) messageBody_;
        }
        return com.example.message.MsgRes.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 4) {
          return msgResBuilder_.getMessage();
        }
        return com.example.message.MsgRes.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    public Builder setMsgRes(com.example.message.MsgRes value) {
      if (msgResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        msgResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    public Builder setMsgRes(
        com.example.message.MsgRes.Builder builderForValue) {
      if (msgResBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        msgResBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    public Builder mergeMsgRes(com.example.message.MsgRes value) {
      if (msgResBuilder_ == null) {
        if (messageBodyCase_ == 4 &&
            messageBody_ != com.example.message.MsgRes.getDefaultInstance()) {
          messageBody_ = com.example.message.MsgRes.newBuilder((com.example.message.MsgRes) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 4) {
          msgResBuilder_.mergeFrom(value);
        }
        msgResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 4;
      return this;
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    public Builder clearMsgRes() {
      if (msgResBuilder_ == null) {
        if (messageBodyCase_ == 4) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 4) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        msgResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    public com.example.message.MsgRes.Builder getMsgResBuilder() {
      return getMsgResFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    @java.lang.Override
    public com.example.message.MsgResOrBuilder getMsgResOrBuilder() {
      if ((messageBodyCase_ == 4) && (msgResBuilder_ != null)) {
        return msgResBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 4) {
          return (com.example.message.MsgRes) messageBody_;
        }
        return com.example.message.MsgRes.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.MsgRes msgRes = 4;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.MsgRes, com.example.message.MsgRes.Builder, com.example.message.MsgResOrBuilder> 
        getMsgResFieldBuilder() {
      if (msgResBuilder_ == null) {
        if (!(messageBodyCase_ == 4)) {
          messageBody_ = com.example.message.MsgRes.getDefaultInstance();
        }
        msgResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.message.MsgRes, com.example.message.MsgRes.Builder, com.example.message.MsgResOrBuilder>(
                (com.example.message.MsgRes) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 4;
      onChanged();;
      return msgResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.LoginRes, com.example.message.LoginRes.Builder, com.example.message.LoginResOrBuilder> loginResBuilder_;
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     * @return Whether the loginRes field is set.
     */
    @java.lang.Override
    public boolean hasLoginRes() {
      return messageBodyCase_ == 5;
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     * @return The loginRes.
     */
    @java.lang.Override
    public com.example.message.LoginRes getLoginRes() {
      if (loginResBuilder_ == null) {
        if (messageBodyCase_ == 5) {
          return (com.example.message.LoginRes) messageBody_;
        }
        return com.example.message.LoginRes.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 5) {
          return loginResBuilder_.getMessage();
        }
        return com.example.message.LoginRes.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    public Builder setLoginRes(com.example.message.LoginRes value) {
      if (loginResBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        loginResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    public Builder setLoginRes(
        com.example.message.LoginRes.Builder builderForValue) {
      if (loginResBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        loginResBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    public Builder mergeLoginRes(com.example.message.LoginRes value) {
      if (loginResBuilder_ == null) {
        if (messageBodyCase_ == 5 &&
            messageBody_ != com.example.message.LoginRes.getDefaultInstance()) {
          messageBody_ = com.example.message.LoginRes.newBuilder((com.example.message.LoginRes) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 5) {
          loginResBuilder_.mergeFrom(value);
        }
        loginResBuilder_.setMessage(value);
      }
      messageBodyCase_ = 5;
      return this;
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    public Builder clearLoginRes() {
      if (loginResBuilder_ == null) {
        if (messageBodyCase_ == 5) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 5) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        loginResBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    public com.example.message.LoginRes.Builder getLoginResBuilder() {
      return getLoginResFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    @java.lang.Override
    public com.example.message.LoginResOrBuilder getLoginResOrBuilder() {
      if ((messageBodyCase_ == 5) && (loginResBuilder_ != null)) {
        return loginResBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 5) {
          return (com.example.message.LoginRes) messageBody_;
        }
        return com.example.message.LoginRes.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.LoginRes loginRes = 5;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.LoginRes, com.example.message.LoginRes.Builder, com.example.message.LoginResOrBuilder> 
        getLoginResFieldBuilder() {
      if (loginResBuilder_ == null) {
        if (!(messageBodyCase_ == 5)) {
          messageBody_ = com.example.message.LoginRes.getDefaultInstance();
        }
        loginResBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.message.LoginRes, com.example.message.LoginRes.Builder, com.example.message.LoginResOrBuilder>(
                (com.example.message.LoginRes) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 5;
      onChanged();;
      return loginResBuilder_;
    }

    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.MsgRX, com.example.message.MsgRX.Builder, com.example.message.MsgRXOrBuilder> msgRXBuilder_;
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     * @return Whether the msgRX field is set.
     */
    @java.lang.Override
    public boolean hasMsgRX() {
      return messageBodyCase_ == 6;
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     * @return The msgRX.
     */
    @java.lang.Override
    public com.example.message.MsgRX getMsgRX() {
      if (msgRXBuilder_ == null) {
        if (messageBodyCase_ == 6) {
          return (com.example.message.MsgRX) messageBody_;
        }
        return com.example.message.MsgRX.getDefaultInstance();
      } else {
        if (messageBodyCase_ == 6) {
          return msgRXBuilder_.getMessage();
        }
        return com.example.message.MsgRX.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    public Builder setMsgRX(com.example.message.MsgRX value) {
      if (msgRXBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        messageBody_ = value;
        onChanged();
      } else {
        msgRXBuilder_.setMessage(value);
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    public Builder setMsgRX(
        com.example.message.MsgRX.Builder builderForValue) {
      if (msgRXBuilder_ == null) {
        messageBody_ = builderForValue.build();
        onChanged();
      } else {
        msgRXBuilder_.setMessage(builderForValue.build());
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    public Builder mergeMsgRX(com.example.message.MsgRX value) {
      if (msgRXBuilder_ == null) {
        if (messageBodyCase_ == 6 &&
            messageBody_ != com.example.message.MsgRX.getDefaultInstance()) {
          messageBody_ = com.example.message.MsgRX.newBuilder((com.example.message.MsgRX) messageBody_)
              .mergeFrom(value).buildPartial();
        } else {
          messageBody_ = value;
        }
        onChanged();
      } else {
        if (messageBodyCase_ == 6) {
          msgRXBuilder_.mergeFrom(value);
        }
        msgRXBuilder_.setMessage(value);
      }
      messageBodyCase_ = 6;
      return this;
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    public Builder clearMsgRX() {
      if (msgRXBuilder_ == null) {
        if (messageBodyCase_ == 6) {
          messageBodyCase_ = 0;
          messageBody_ = null;
          onChanged();
        }
      } else {
        if (messageBodyCase_ == 6) {
          messageBodyCase_ = 0;
          messageBody_ = null;
        }
        msgRXBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    public com.example.message.MsgRX.Builder getMsgRXBuilder() {
      return getMsgRXFieldBuilder().getBuilder();
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    @java.lang.Override
    public com.example.message.MsgRXOrBuilder getMsgRXOrBuilder() {
      if ((messageBodyCase_ == 6) && (msgRXBuilder_ != null)) {
        return msgRXBuilder_.getMessageOrBuilder();
      } else {
        if (messageBodyCase_ == 6) {
          return (com.example.message.MsgRX) messageBody_;
        }
        return com.example.message.MsgRX.getDefaultInstance();
      }
    }
    /**
     * <code>.chat.simple.MsgRX msgRX = 6;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.example.message.MsgRX, com.example.message.MsgRX.Builder, com.example.message.MsgRXOrBuilder> 
        getMsgRXFieldBuilder() {
      if (msgRXBuilder_ == null) {
        if (!(messageBodyCase_ == 6)) {
          messageBody_ = com.example.message.MsgRX.getDefaultInstance();
        }
        msgRXBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.example.message.MsgRX, com.example.message.MsgRX.Builder, com.example.message.MsgRXOrBuilder>(
                (com.example.message.MsgRX) messageBody_,
                getParentForChildren(),
                isClean());
        messageBody_ = null;
      }
      messageBodyCase_ = 6;
      onChanged();;
      return msgRXBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:chat.simple.Message)
  }

  // @@protoc_insertion_point(class_scope:chat.simple.Message)
  private static final com.example.message.Message DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.example.message.Message();
  }

  public static com.example.message.Message getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Message>
      PARSER = new com.google.protobuf.AbstractParser<Message>() {
    @java.lang.Override
    public Message parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Message(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Message> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Message> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.example.message.Message getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

