// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

public final class MessageProto {
  private MessageProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_simple_Message_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_simple_Message_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_simple_LoginReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_simple_LoginReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_simple_LoginRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_simple_LoginRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_simple_MsgReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_simple_MsgReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_simple_MsgRes_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_simple_MsgRes_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_chat_simple_MsgRX_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_chat_simple_MsgRX_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n+small_chat/src/main/resources/message." +
      "proto\022\013chat.simple\"\353\002\n\007Message\0225\n\013messag" +
      "eType\030\001 \001(\0162 .chat.simple.Message.Messag" +
      "eType\022)\n\010loginReq\030\002 \001(\0132\025.chat.simple.Lo" +
      "ginReqH\000\022%\n\006msgReq\030\003 \001(\0132\023.chat.simple.M" +
      "sgReqH\000\022%\n\006msgRes\030\004 \001(\0132\023.chat.simple.Ms" +
      "gResH\000\022)\n\010loginRes\030\005 \001(\0132\025.chat.simple.L" +
      "oginResH\000\022#\n\005msgRX\030\006 \001(\0132\022.chat.simple.M" +
      "sgRXH\000\"Q\n\013MessageType\022\r\n\tLOGIN_REQ\020\000\022\r\n\t" +
      "LOGIN_RES\020\001\022\013\n\007MSG_REQ\020\002\022\013\n\007MSG_RES\020\003\022\n\n" +
      "\006MSG_RX\020\004B\r\n\013messageBody\",\n\010LoginReq\022\016\n\006" +
      "userId\030\001 \001(\005\022\020\n\010username\030\002 \001(\t\"\205\001\n\010Login" +
      "Res\0221\n\006status\030\001 \001(\0162!.chat.simple.LoginR" +
      "es.LoginStatus\022\020\n\010response\030\002 \001(\t\022\016\n\006user" +
      "Id\030\003 \001(\005\"$\n\013LoginStatus\022\013\n\007SUCCESS\020\000\022\010\n\004" +
      "FAIL\020\001\"7\n\006MsgReq\022\017\n\007sUserId\030\001 \001(\005\022\017\n\007dUs" +
      "erId\030\002 \001(\005\022\013\n\003msg\030\003 \001(\t\"g\n\006MsgRes\022*\n\006sta" +
      "tus\030\001 \001(\0162\032.chat.simple.MsgRes.Status\022\020\n" +
      "\010response\030\002 \001(\t\"\037\n\006Status\022\013\n\007SUCCESS\020\000\022\010" +
      "\n\004FAIL\020\001\")\n\005MsgRX\022\017\n\007content\030\001 \001(\t\022\017\n\007sU" +
      "serId\030\002 \001(\005B%\n\023com.example.messageB\014Mess" +
      "ageProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_chat_simple_Message_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_chat_simple_Message_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_simple_Message_descriptor,
        new java.lang.String[] { "MessageType", "LoginReq", "MsgReq", "MsgRes", "LoginRes", "MsgRX", "MessageBody", });
    internal_static_chat_simple_LoginReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_chat_simple_LoginReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_simple_LoginReq_descriptor,
        new java.lang.String[] { "UserId", "Username", });
    internal_static_chat_simple_LoginRes_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_chat_simple_LoginRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_simple_LoginRes_descriptor,
        new java.lang.String[] { "Status", "Response", "UserId", });
    internal_static_chat_simple_MsgReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_chat_simple_MsgReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_simple_MsgReq_descriptor,
        new java.lang.String[] { "SUserId", "DUserId", "Msg", });
    internal_static_chat_simple_MsgRes_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_chat_simple_MsgRes_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_simple_MsgRes_descriptor,
        new java.lang.String[] { "Status", "Response", });
    internal_static_chat_simple_MsgRX_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_chat_simple_MsgRX_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_chat_simple_MsgRX_descriptor,
        new java.lang.String[] { "Content", "SUserId", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
