// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

public interface MessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.Message)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chat.simple.Message.MessageType messageType = 1;</code>
   * @return The enum numeric value on the wire for messageType.
   */
  int getMessageTypeValue();
  /**
   * <code>.chat.simple.Message.MessageType messageType = 1;</code>
   * @return The messageType.
   */
  com.example.message.Message.MessageType getMessageType();

  /**
   * <code>.chat.simple.LoginReq loginReq = 2;</code>
   * @return Whether the loginReq field is set.
   */
  boolean hasLoginReq();
  /**
   * <code>.chat.simple.LoginReq loginReq = 2;</code>
   * @return The loginReq.
   */
  com.example.message.LoginReq getLoginReq();
  /**
   * <code>.chat.simple.LoginReq loginReq = 2;</code>
   */
  com.example.message.LoginReqOrBuilder getLoginReqOrBuilder();

  /**
   * <code>.chat.simple.MsgReq msgReq = 3;</code>
   * @return Whether the msgReq field is set.
   */
  boolean hasMsgReq();
  /**
   * <code>.chat.simple.MsgReq msgReq = 3;</code>
   * @return The msgReq.
   */
  com.example.message.MsgReq getMsgReq();
  /**
   * <code>.chat.simple.MsgReq msgReq = 3;</code>
   */
  com.example.message.MsgReqOrBuilder getMsgReqOrBuilder();

  /**
   * <code>.chat.simple.MsgRes msgRes = 4;</code>
   * @return Whether the msgRes field is set.
   */
  boolean hasMsgRes();
  /**
   * <code>.chat.simple.MsgRes msgRes = 4;</code>
   * @return The msgRes.
   */
  com.example.message.MsgRes getMsgRes();
  /**
   * <code>.chat.simple.MsgRes msgRes = 4;</code>
   */
  com.example.message.MsgResOrBuilder getMsgResOrBuilder();

  /**
   * <code>.chat.simple.LoginRes loginRes = 5;</code>
   * @return Whether the loginRes field is set.
   */
  boolean hasLoginRes();
  /**
   * <code>.chat.simple.LoginRes loginRes = 5;</code>
   * @return The loginRes.
   */
  com.example.message.LoginRes getLoginRes();
  /**
   * <code>.chat.simple.LoginRes loginRes = 5;</code>
   */
  com.example.message.LoginResOrBuilder getLoginResOrBuilder();

  /**
   * <code>.chat.simple.MsgRX msgRX = 6;</code>
   * @return Whether the msgRX field is set.
   */
  boolean hasMsgRX();
  /**
   * <code>.chat.simple.MsgRX msgRX = 6;</code>
   * @return The msgRX.
   */
  com.example.message.MsgRX getMsgRX();
  /**
   * <code>.chat.simple.MsgRX msgRX = 6;</code>
   */
  com.example.message.MsgRXOrBuilder getMsgRXOrBuilder();

  public com.example.message.Message.MessageBodyCase getMessageBodyCase();
}
