// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface MsgRXOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.MsgRX)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string content = 1;</code>
   * @return The content.
   */
  java.lang.String getContent();
  /**
   * <code>string content = 1;</code>
   * @return The bytes for content.
   */
  com.google.protobuf.ByteString
      getContentBytes();

  /**
   * <code>string sUsername = 2;</code>
   * @return The sUsername.
   */
  java.lang.String getSUsername();
  /**
   * <code>string sUsername = 2;</code>
   * @return The bytes for sUsername.
   */
  com.google.protobuf.ByteString
      getSUsernameBytes();
}
