// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

public interface MsgReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.MsgReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 sUserId = 1;</code>
   * @return The sUserId.
   */
  int getSUserId();

  /**
   * <code>int32 dUserId = 2;</code>
   * @return The dUserId.
   */
  int getDUserId();

  /**
   * <code>string msg = 3;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 3;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
