// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/message.proto

package com.example.message;

public interface MsgReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.MsgReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string dUsername = 2;</code>
   * @return The dUsername.
   */
  java.lang.String getDUsername();
  /**
   * <code>string dUsername = 2;</code>
   * @return The bytes for dUsername.
   */
  com.google.protobuf.ByteString
      getDUsernameBytes();

  /**
   * <code>string msg = 3;</code>
   * @return The msg.
   */
  java.lang.String getMsg();
  /**
   * <code>string msg = 3;</code>
   * @return The bytes for msg.
   */
  com.google.protobuf.ByteString
      getMsgBytes();
}
