// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: small_chat/src/main/resources/message.proto

package com.example.message;

public interface MsgResOrBuilder extends
    // @@protoc_insertion_point(interface_extends:chat.simple.MsgRes)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.chat.simple.MsgRes.Status status = 1;</code>
   * @return The enum numeric value on the wire for status.
   */
  int getStatusValue();
  /**
   * <code>.chat.simple.MsgRes.Status status = 1;</code>
   * @return The status.
   */
  com.example.message.MsgRes.Status getStatus();

  /**
   * <code>string response = 2;</code>
   * @return The response.
   */
  java.lang.String getResponse();
  /**
   * <code>string response = 2;</code>
   * @return The bytes for response.
   */
  com.google.protobuf.ByteString
      getResponseBytes();
}
